Repository dataware-tools/app-common, pull requests merged in 2021-07, with the labels that each got.

#71 Fix `repository` in package.json
  package.json
Labels: approved, size/XS

#72 Disable baseUrl
  src/api/catalog.ts
  src/app/catalog.ts
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/MultiSelect.tsx
  src/components/PerPageSelect.tsx
  src/components/Sample.test.tsx
  src/components/Sample.tsx
  src/components/TabBar.tsx
  src/components/TableRow.tsx
  src/components/dialog/DialogCloseButton.tsx
  src/test-utils.tsx
  src/utils/window.tsx
  tsconfig.json
Labels: approved, lgtm, size/S

#73 Remove UseAPI
  src/api/fetchClient.tsx
Labels: approved, lgtm, size/L

#74 Apply theme to ConfirmModal
  src/utils/window.tsx
Labels: approved, lgtm, size/M

#75 Update package version
  package.json
Labels: approved, lgtm, size/XS

#76 Use M-ui system prop for layouting page and dialog
  .storybook/preview.js
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/dialog/DialogBody.tsx
  src/components/dialog/DialogContainer.tsx
  src/components/dialog/DialogMain.tsx
  src/components/dialog/DialogTemplate.stories.tsx
  src/components/dialog/DialogTemplate.tsx
  src/components/dialog/DialogWrapper.tsx
  src/components/page/PageBody.tsx
  src/components/page/PageContainer.tsx
  src/components/page/PageMain.tsx
  src/components/page/PageWrapper.tsx
Labels: approved, lgtm, size/L

#78 Fix bug that theme is null
  src/components/dialog/DialogCloseButton.tsx
Labels: approved, size/XS

#79 Add DataGrid theme
  src/theme.ts
Labels: approved, lgtm, size/S

#80 Increment package version
  package.json
Labels: approved, lgtm, size/XS
