Repository dataware-tools/app-common, pull requests merged in 2021-12, with the labels that each got.

#124 Remove outdated files and packages
  bin/generate_openapi.sh
  package-lock.json
  package.json
  src/api/fetchClient.tsx
  src/api/index.ts
  src/api/utils.tsx
  src/index.ts
  src/openapi/.gitignore
Labels: size/XXL, approved, lgtm

#129 Bump MUI
  package-lock.json
  package.json
Labels: size/XXL, approved, lgtm

#137 Use node 16 instead of 14
  .github/workflows/auto-release.yml
Labels: approved, lgtm

#138 Bump package version
  package-lock.json
  package.json
Labels: approved, lgtm

#139 [skip ci] Stop releasing when branch name contains "depandabot"
  .github/workflows/auto-release.yml
Labels: approved, lgtm

#145 Drop support for Node 10
  .github/workflows/test.yaml
  package.json
Labels: size/XS, approved, lgtm

#146 Add CI to test apps which use app-common
  .github/workflows/test-apps.yaml
Labels: size/M, approved, lgtm

#144 Fix deps
  .eslintrc.js
  .loki/reference/chrome_laptop_FileUploadButton_Default.png
  .loki/reference/chrome_laptop_TabBar_Default.png
  .storybook/main.js
  .stylelintrc.js
  jest.config.js
  package-lock.json
  package.json
  src/components/MultiSelect.tsx
  src/setupTest.ts
  src/test-utils.tsx
  src/theme.ts
Labels: size/XXL, approved, lgtm, do-not-merge/invalid-commit-message

#150 Stop automatic release when Dependabot push
  .github/workflows/auto-release.yml
Labels: size/XS, approved, lgtm

#152 Add CI for automaticaly merging dependabot patch update
  .github/workflows/auto-merge.yml
Labels: approved, lgtm, size/S

#157 Add test app
  .github/workflows/test-apps.yaml
Labels: size/XS, approved, lgtm
