Repository dataware-tools/app-common, pull requests merged in 2021-08, with the labels that each got.

#82 Add util for fetching
  src/api/fetchClient.tsx
Labels: approved

#83 Support cancenl closing ConfirmModal
  src/components/ConfimModal.stories.tsx
  src/components/ConfirmModal.tsx
  src/components/ConfirmModalBase.tsx
  src/utils/window.tsx
Labels: size/M, approved

#84 Add inputProps to SearchForm props
  src/components/SearchForm.tsx
Labels: size/XS, approved

#86 Add delete mode to confirm modal
  src/components/ConfimModal.stories.tsx
  src/components/ConfirmModal.tsx
Labels: size/M, approved, lgtm

#85 Add utility for extracting common error message from fetch error
  src/api/fetchClient.tsx
Labels: size/M, approved

#87 Bump Material-UI to beta.4
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/ConfimModal.stories.tsx
  src/components/ConfirmModal.tsx
  src/components/ErrorMessage.tsx
  src/components/FileUploadButton.stories.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/LoadingIndicator.tsx
  src/components/MultiSelect.tsx
  src/components/NoticeableLetters.tsx
  src/components/PerPageSelect.tsx
  src/components/Sample.tsx
  src/components/SquareIconButton.tsx
  src/components/TabBar.tsx
  src/components/TableRow.tsx
  src/components/TextCenteringSpan.tsx
  src/components/ToolBar.tsx
  src/components/dialog/DialogBody.tsx
  src/components/dialog/DialogCloseButton.tsx
  src/components/dialog/DialogContainer.tsx
  src/components/dialog/DialogMain.tsx
  src/components/dialog/DialogSubTitle.tsx
  src/components/dialog/DialogTabBar.tsx
  src/components/dialog/DialogTitle.tsx
  src/components/dialog/DialogToolBar.tsx
  src/components/dialog/DialogWrapper.tsx
  src/components/page/PageBody.tsx
  src/components/page/PageContainer.tsx
  src/components/page/PageMain.tsx
  src/components/page/PageTabBar.tsx
  src/components/page/PageToolBar.tsx
  src/components/page/PageWrapper.tsx
  src/test-utils.tsx
  src/theme.ts
Labels: approved, lgtm, size/XL

#90 Fix code format of misc config file
  .prettierignore
  .stylelintrc.js
  README.md
  jest.config.js
  lint-staged.config.js
Labels: approved
