Repository dataware-tools/app-common, pull requests merged in 2022-03, with the labels that each got.

#302 Fix color of line in FilterSelector
  src/components/FilterSelector.tsx
Labels: size/XS, approved, lgtm

#308 Support changing font
  .storybook/preview.js
  src/components/MultiSelect.tsx
  src/index.ts
  src/test-utils.tsx
  src/theme.ts
  src/utils/window.tsx
Labels: size/L, approved, lgtm

#301 Improve UX of search box with hitsory
  src/components/SearchForm.tsx
Labels: approved, size/S

#322 Add component RecursiveFilterSelector
  .loki/reference/chrome_laptop_RecursiveFilterSelectorList_Controlled.png
  .loki/reference/chrome_laptop_RecursiveFilterSelectorList_Default.png
  .loki/reference/chrome_laptop_RecursiveFilterSelector_Controlled.png
  .loki/reference/chrome_laptop_RecursiveFilterSelector_Default.png
  .loki/reference/chrome_laptop_RecursiveFilterSelector_Disable_Collapse.png
  src/components/RecursiveFilterSelector.stories.tsx
  src/components/RecursiveFilterSelector.test.tsx
  src/components/RecursiveFilterSelector.tsx
  src/components/RecursiveFilterSelectorList.stories.tsx
  src/components/RecursiveFilterSelectorList.test.tsx
  src/components/RecursiveFilterSelectorList.tsx
  src/index.ts
Labels: approved, size/XL

#329 Fix the test of MultiSelect
  src/components/MultiSelect.test.tsx
  src/components/MultiSelect.tsx
Labels: size/XS, approved

#328 Fix size and spaces of RecursiveFilterSelector
  .loki/reference/chrome_laptop_RecursiveFilterSelectorList_Controlled.png
  .loki/reference/chrome_laptop_RecursiveFilterSelectorList_Default.png
  .loki/reference/chrome_laptop_RecursiveFilterSelector_Controlled.png
  .loki/reference/chrome_laptop_RecursiveFilterSelector_Default.png
  .loki/reference/chrome_laptop_RecursiveFilterSelector_Disable_Collapse.png
  src/components/RecursiveFilterSelector.tsx
  src/components/RecursiveFilterSelectorList.tsx
Labels: size/XS, approved
